# cli-plan.yml
#
# Generated by the Takeover stage while backfilling an existing project and
# consumed by Extend, Validate, and Publish as the authoritative adopted CLI
# contract. Stored at: <target-project>/.cli-forge/cli-plan.yml

skill_name: "{{skill_name}}"
design_contract: "./design-contract.yml"

invocation:
  shipped: "{{observed_shipped_invocation}}"
  dev: "{{observed_dev_invocation_or_none}}"
  release_binary: "{{observed_release_binary_invocation_or_none}}"

commands:
  - name: "{{command_name}}"
    description: "{{command_description}}"
    flags:
      - name: "{{--flag-name}}"
        type: "{{string|path|bool|enum|int}}"
        required: "{{true|false}}"
        default: "{{default_value}}"
        values: []
        description: "{{flag_description}}"
    # Preserve the formats this command actually supports today. Do not
    # expand to cli-forge defaults unless the implementation already does so.
    output_formats:
      - "{{observed_output_format_1_or_none}}"
      - "{{observed_output_format_2_or_none}}"
      - "{{observed_output_format_3_or_none}}"
    error_format: "{{observed_error_format_for_command}}"

  # Add a `help` command entry here only when the adopted project actually
  # exposes one. Do not backfill cli-forge-standard structured-help flags or
  # formats unless they are evidenced in the implementation today.

help:
  # Record the help behavior observed in the adopted project exactly as it
  # exists today. Do not silently upgrade these fields to cli-forge defaults
  # during takeover; Validate is responsible for surfacing any standards drift.
  leaf_default: "{{observed_leaf_help_behavior}}"
  non_leaf_default: "{{observed_non_leaf_help_behavior}}"
  flag: "{{observed_help_flag_behavior}}"
  subcommand: "{{observed_help_subcommand_behavior}}"
  human_readable_format:
    style: "{{observed_human_help_style}}"
    required_sections:
      - "{{observed_section_1_or_none}}"
      - "{{observed_section_2_or_none}}"
      - "{{observed_section_3_or_none}}"
      - "{{observed_section_4_or_none}}"
      - "{{observed_section_5_or_none}}"
      - "{{observed_section_6_or_none}}"
      - "{{observed_section_7_or_none}}"
    section_order: "{{observed_human_help_section_order}}"

capabilities:
  stream: "{{in_scope|out_of_scope}}"
  repl: "{{in_scope|out_of_scope}}"
  daemon: "{{in_scope|out_of_scope}}"

runtime:
  directories:
    config: "{{observed_config_directory_behavior_or_none}}"
    data: "{{observed_data_directory_behavior_or_none}}"
    state: "{{observed_state_directory_behavior_or_none}}"
    cache: "{{observed_cache_directory_behavior_or_none}}"
    logs: "{{observed_logs_directory_behavior_or_none}}"
  scope: "{{observed_runtime_scope}}"
  # List only the runtime override flags that the adopted project actually
  # exposes today. Leave empty when no standardized override surface exists.
  overrides:
    - "{{observed_runtime_override_flag_1_or_none}}"
    - "{{observed_runtime_override_flag_2_or_none}}"
    - "{{observed_runtime_override_flag_3_or_none}}"
    - "{{observed_runtime_override_flag_4_or_none}}"
    - "{{observed_runtime_override_flag_5_or_none}}"
  active_context:
    supported: "{{true|false}}"
    inspect_command: "{{observed_active_context_inspect_command_or_none}}"
    persist_command: "{{observed_active_context_persist_command_or_none}}"
    per_invocation_overrides:
      - "{{observed_context_override_1_or_none}}"
      - "{{observed_context_override_2_or_none}}"
    precedence: "{{observed_active_context_precedence_or_none}}"

daemon_contract:
  enabled: "{{true|false}}"

# When capabilities.daemon is out_of_scope, keep daemon_contract as the
# minimal single-field block above and do not add daemon commands or
# daemon-routing flags anywhere else in cli-plan.yml.
#
# When capabilities.daemon is in_scope, replace the minimal block above with:
#
# daemon_contract:
#   enabled: true
#   mode: "app_server"
#   instance_model: "single"
#   lifecycle:
#     foreground:
#       - "run"
#     background:
#       - "start"
#       - "stop"
#       - "restart"
#       - "status"
#   daemonizable_commands:
#     - "{{command_name}}"
#   client_routing:
#     execution_flag:
#       name: "--via"
#       values: ["local", "daemon"]
#       default: "local"
#     ensure_daemon_flag:
#       name: "--ensure-daemon"
#       requires: "--via daemon"
#     local_only_commands:
#       - "help"
#       - "paths"
#       - "context"
#       - "daemon"
#   transports:
#     local_default: "unix_socket_or_named_pipe"
#     tcp: "opt_in_loopback_only"
#   auth:
#     local_ipc: "os_permissions"
#     tcp: "required_when_enabled"
#   rpc:
#     protocol: "json_rpc_2_0"
#     methods:
#       - "daemon.health"
#       - "daemon.status"
#       - "daemon.shutdown"
#       - "command.execute"
#       - "command.execute_stream"
#   status_fields:
#     - "state"
#     - "readiness"
#     - "instance_id"
#     - "pid"
#     - "transport"
#     - "endpoint"
#     - "uptime_sec"
#     - "active_requests"
#     - "queue_depth"
#     - "last_error"
#     - "recommended_next_action"
#   return_on:
#     start: ["running", "failed", "timeout"]
#     stop: ["stopped", "failed", "timeout"]
#     restart: ["running", "failed", "timeout"]
#     run: ["stopped", "failed"]
#   recovery: "client_uses_status_stop_restart_and_structured_errors"
#   streaming:
#     rpc_method: "command.execute_stream"
#     json: "ndjson"
#     yaml: "multi_document"
#     toml: "unsupported_unless_explicitly_planned"
#   runtime_artifacts:
#     directory: "state/daemon"
#     files:
#       - "daemon.pid"
#       - "daemon.sock_or_pipe_metadata"
#       - "daemon-state.json"
#       - "daemon.log"
#       - "daemon.lock"
#       - "auth.token_when_tcp_enabled"

approved_by: "{{user}}"
approved_at: "{{iso8601_timestamp}}"
