# design-contract.yml
#
# Generated by the Takeover stage while backfilling an existing project and
# consumed by downstream planning, validation, and release work. Stored at:
# <target-project>/.cli-forge/design-contract.yml

skill_name: "{{skill_name}}"
purpose: "{{single_line_purpose_summary}}"
positioning: "{{positioning_statement_paragraph}}"

sync_surfaces:
  - "Cargo.toml package.description"
  - "SKILL.md purpose section"
  - "README.md header and description"
  - "help text summary line across non-leaf auto-help, `--help`, and structured `help`"
  - "release notes summary (when publish is in scope)"
  - "npm package description (when publish is in scope)"

help_contract:
  # Record the adopted help contract as currently implemented. Validate will
  # surface any drift from cli-forge standards after takeover.
  leaf_missing_required_input: "{{observed_leaf_missing_required_input_behavior}}"
  non_leaf_default: "{{observed_non_leaf_default_behavior}}"
  help_flag: "{{observed_help_flag_behavior}}"
  help_subcommand: "{{observed_help_subcommand_behavior}}"
  human_readable_help:
    style: "{{observed_human_help_style}}"
    section_order:
      - "{{observed_help_section_1_or_none}}"
      - "{{observed_help_section_2_or_none}}"
      - "{{observed_help_section_3_or_none}}"
      - "{{observed_help_section_4_or_none}}"
      - "{{observed_help_section_5_or_none}}"
      - "{{observed_help_section_6_or_none}}"
      - "{{observed_help_section_7_or_none}}"

publish_contract:
  stage: "publish"
  channels:
    - "repo_native"
    - "npm"

approved_by: "{{user}}"
approved_at: "{{iso8601_timestamp}}"
