# takeover-receipt.yml
#
# Generated by the Takeover recovery stage after reconstructing cli-forge
# contracts for an existing project. Stored at:
# <target-project>/.cli-forge/takeover-receipt.yml

project: "{{skill_name}}"
project_path: "{{project_path}}"
timestamp: "{{iso8601_timestamp}}"

baseline_origin: "existing_project"
baseline_status: "adopted"

artifacts_generated:
  - "./design-contract.yml"
  - "./cli-plan.yml"
  - "./takeover-receipt.yml"

router_handoff_ref: "./handoff.yml"

baseline_equivalence:
  usable_for:
    - "validate"
    - "publish"
  extend_layout_compatible: "{{true_or_false}}"
  extend_layout_required_files:
    - "Cargo.toml"
    - "SKILL.md"
    - "src/main.rs"
    - "src/lib.rs"
    - "src/help.rs"
    - "src/context.rs"
    - "tests/cli_test.rs"
  not_a_scaffold_receipt: true

evidence_sources:
  - "{{evidence_source_1}}"
  - "{{evidence_source_2_or_none}}"
  - "{{evidence_source_3_or_none}}"
  - "{{evidence_source_4_or_none}}"
  - "{{evidence_source_5_or_none}}"
  - "{{evidence_source_6_or_none}}"

user_decisions:
  - question: "{{question_or_none}}"
    decision: "{{decision_or_none}}"

follow_up_required:
  - "{{optional_follow_up_or_none}}"

post_adoption_objective: "{{validate|extend|publish|general_adoption}}"
takeover_mode: "{{first_adoption|baseline_establishment|contract_refresh}}"
design_contract_rewritten: "{{true_or_false}}"
cli_plan_rewritten: "{{true_or_false}}"
gitignore_rewritten: "{{true_or_false}}"
validation_covered_baseline_changed: "{{true_or_false}}"
validation_report_status_after_takeover: "{{fresh_compliant|fresh_warning|stale_due_to_contract_or_baseline_change|missing|other}}"
next_stage: "{{validate|publish|extend|blocked_normalization_required|blocked_pending_user|blocked_missing_evidence}}"
next_stage_reason: "{{why_this_stage_was_selected}}"
outcome: "{{adopted|blocked_pending_user|blocked_missing_evidence|blocked_normalization_required}}"
