# extend-receipt.yml
#
# Generated by the Extend stage (Stage 4) after successfully adding a feature.
# Consumed by the Validate stage (Stage 5).
# Stored at: <target-project>/.cli-forge/extend-receipt.yml

skill_name: "{{skill_name}}"
cli_plan_ref: "./cli-plan.yml"
timestamp: "{{iso8601_timestamp}}"

feature: "{{stream|repl|daemon}}"
template_source: "templates/"

files_added:
  - "{{file_path}}"

files_modified:
  - "{{file_path}}"

cli_plan_updated: "{{true|false}}"

verification:
  cargo_build: "{{pass|fail}}"
  cargo_clippy: "{{pass|fail}}"
  cargo_fmt: "{{pass|fail}}"
  cargo_test: "{{pass|fail}}"

all_passed: "{{true|false}}"
