# handoff.yml
#
# Generated by the cli-forge Router (Stage 0) and consumed by the target
# downstream stage. Stored at: <target-project>/.cli-forge/handoff.yml

stage_from: "router"
stage_to: "{{next_stage}}"           # design | plan | scaffold | extend | validate | publish | distribute
timestamp: "{{iso8601_timestamp}}"
classification: "{{classification}}" # design | plan | scaffold | extend | validate | publish | distribute

inputs:
  skill_name: "{{skill_name}}"
  project_path: "{{project_path}}"
  feature: "{{feature}}"             # stream | repl (for extend); daemon requests route to plan
  publish_mode: "{{mode}}"           # report_only | dry_run | rehearsal | live_release (only for publish/distribute)
  publish_channel: "{{channel}}"     # repo_native | npm | both (only for publish/distribute)

validation_status: "{{current|stale|missing}}"
notes: "{{free_text}}"
