# scaffold-receipt.yml
#
# Generated by the Scaffold stage (Stage 3) after successful project creation.
# Consumed by the Validate stage (Stage 5).
# Stored at: <target-project>/.cli-forge/scaffold-receipt.yml

skill_name: "{{skill_name}}"
cli_plan_ref: "./cli-plan.yml"
timestamp: "{{iso8601_timestamp}}"

template_source: "templates/"
files_generated:
  - "Cargo.toml"
  - "src/main.rs"
  - "src/lib.rs"
  - "src/help.rs"
  - "src/context.rs"
  - "SKILL.md"
  - "tests/cli_test.rs"
  - "README.md"

unresolved_tokens: 0

# Capabilities marked in_scope in cli-plan.yml but not generated by scaffold.
# These must be added by the Extend stage (cli-forge-extend) before validation.
deferred_capabilities: []  # e.g. ["stream", "repl", "daemon"]

verification:
  cargo_build: "{{pass|fail}}"
  cargo_clippy: "{{pass|fail}}"
  cargo_fmt: "{{pass|fail}}"
  cargo_test: "{{pass|fail}}"

all_passed: "{{true|false}}"
