# validation-report.yml
#
# Generated by the Validate stage (Stage 5) after running all compliance
# checks. Consumed by Publish (Stage 6).
# Stored at: <target-project>/.cli-forge/validation-report.yml

project: "{{skill_name}}"
project_path: "{{project_path}}"
cli_plan_ref: "./cli-plan.yml"
timestamp: "{{iso8601_timestamp}}"

provenance:
  design_contract_ref: "./design-contract.yml"
  design_contract_receipt: "{{design_contract_receipt}}"
  cli_plan_receipt: "{{cli_plan_receipt}}"
  baseline_receipt_ref: "{{./scaffold-receipt.yml|./takeover-receipt.yml}}"
  baseline_receipt: "{{baseline_receipt}}"
  extend_receipt_ref: "{{./extend-receipt.yml|none}}"
  extend_receipt: "{{extend_receipt_or_none}}"
  contract_set_receipt: "{{contract_set_receipt}}"

result: "{{compliant|warning|non_compliant}}"

checks:
  - id: "{{CHECK-ID}}"
    category: "{{category}}"
    description: "{{check_description}}"
    result: "{{PASS|WARN|FAIL}}"
    detail: "{{optional_detail}}"

summary:
  total: 46
  pass: "{{count}}"
  warn: "{{count}}"
  fail: "{{count}}"

blockers:
  - "{{blocker_description}}"

warnings:
  - "{{warning_description}}"

recommendations:
  - "{{recommendation}}"
