# validation-report.yml
#
# Generated by the Validate stage (Stage 5) after running all compliance
# checks. Consumed by Publish (Stage 6).
# Stored at: <target-project>/.cli-forge/validation-report.yml

project: "{{skill_name}}"
project_path: "{{project_path}}"
cli_plan_ref: "./cli-plan.yml"
timestamp: "{{iso8601_timestamp}}"

result: "{{compliant|warning|non_compliant}}"

checks:
  - id: "{{CHECK-ID}}"
    category: "{{category}}"
    description: "{{check_description}}"
    result: "{{PASS|WARN|FAIL}}"
    detail: "{{optional_detail}}"

summary:
  total: 46
  pass: "{{count}}"
  warn: "{{count}}"
  fail: "{{count}}"

blockers:
  - "{{blocker_description}}"

warnings:
  - "{{warning_description}}"

recommendations:
  - "{{recommendation}}"
