# design-contract.yml
#
# Generated by the Design stage (Stage 1) and consumed by the Plan stage
# (Stage 2). Stored at: <target-project>/.cli-forge/design-contract.yml

skill_name: "{{skill_name}}"
purpose: "{{single_line_purpose_summary}}"
positioning: "{{positioning_statement_paragraph}}"

sync_surfaces:
  - "Cargo.toml package.description"
  - "SKILL.md purpose section"
  - "README.md header and description"
  - "help text summary line"
  - "release notes summary (when publish is in scope)"
  - "npm package description (when publish is in scope)"

publish_contract:
  stage: "publish"
  channels:
    - "repo_native"
    - "npm"

approved_by: "{{user}}"
approved_at: "{{iso8601_timestamp}}"
