# cli-plan.yml
#
# Generated by the Plan stage (Stage 2) and consumed by Scaffold (Stage 3),
# Extend (Stage 4), and Validate (Stage 5) as the authoritative CLI contract.
# Stored at: <target-project>/.cli-forge/cli-plan.yml

skill_name: "{{skill_name}}"
design_contract: "./design-contract.yml"

invocation:
  shipped: "{{skill_name}}"
  dev: "cargo run --"
  release_binary: "./target/release/{{skill_name}}"

commands:
  - name: "{{command_name}}"
    description: "{{command_description}}"
    flags:
      - name: "{{--flag-name}}"
        type: "{{string|path|bool|enum|int}}"
        required: "{{true|false}}"
        default: "{{default_value}}"
        values: []                    # only for enum type
        description: "{{flag_description}}"
    output_formats: ["yaml", "json", "toml"]
    error_format: "structured_stderr"

  - name: "help"
    description: "Structured help output"
    flags:
      - name: "--format"
        type: "enum"
        required: false
        default: "yaml"
        values: ["yaml", "json", "toml"]
        description: "Output format for structured help"

help:
  plain_text: "--help flag on any command"
  structured: "help subcommand with --format"

capabilities:
  stream: "{{in_scope|out_of_scope}}"
  repl: "{{in_scope|out_of_scope}}"
  daemon: "{{in_scope|out_of_scope}}"

runtime:
  directories:
    config: "platform default user-scoped config directory"
    data: "platform default user-scoped data directory"
    state: "derived from data directory by default"
    cache: "platform default user-scoped cache directory"
    logs: "state/logs when logging is enabled"
  scope: "user_scoped_default"
  overrides:
    - "--config-dir"
    - "--data-dir"
    - "--state-dir"
    - "--cache-dir"
    - "--log-dir"
  active_context:
    supported: "{{true|false}}"
    inspect_command: "{{skill_name}} context show"
    persist_command: "{{skill_name}} context use --selector workspace=demo"
    per_invocation_overrides:
      - "--selector KEY=VALUE"
      - "--cwd PATH"
    precedence: "explicit invocation values override the persisted Active Context for one invocation only"

daemon_contract:
  enabled: "{{true|false}}"

# When capabilities.daemon is out_of_scope, keep daemon_contract as the
# minimal single-field block above and do not add daemon commands or
# daemon-routing flags anywhere else in cli-plan.yml.
#
# When capabilities.daemon is in_scope, replace the minimal block above with:
#
# daemon_contract:
#   enabled: true
#   mode: "app_server"
#   instance_model: "single"
#   lifecycle:
#     foreground:
#       - "run"
#     background:
#       - "start"
#       - "stop"
#       - "restart"
#       - "status"
#   daemonizable_commands:
#     - "{{command_name}}"
#   client_routing:
#     execution_flag:
#       name: "--via"
#       values: ["local", "daemon"]
#       default: "local"
#     ensure_daemon_flag:
#       name: "--ensure-daemon"
#       requires: "--via daemon"
#     local_only_commands:
#       - "help"
#       - "paths"
#       - "context"
#       - "daemon"
#   transports:
#     local_default: "unix_socket_or_named_pipe"
#     tcp: "opt_in_loopback_only"
#   auth:
#     local_ipc: "os_permissions"
#     tcp: "required_when_enabled"
#   rpc:
#     protocol: "json_rpc_2_0"
#     methods:
#       - "daemon.health"
#       - "daemon.status"
#       - "daemon.shutdown"
#       - "command.execute"
#       - "command.execute_stream"
#   status_fields:
#     - "state"
#     - "readiness"
#     - "instance_id"
#     - "pid"
#     - "transport"
#     - "endpoint"
#     - "uptime_sec"
#     - "active_requests"
#     - "queue_depth"
#     - "last_error"
#     - "recommended_next_action"
#   return_on:
#     start: ["running", "failed", "timeout"]
#     stop: ["stopped", "failed", "timeout"]
#     restart: ["running", "failed", "timeout"]
#     run: ["stopped", "failed"]
#   recovery: "client_uses_status_stop_restart_and_structured_errors"
#   streaming:
#     rpc_method: "command.execute_stream"
#     json: "ndjson"
#     yaml: "multi_document"
#     toml: "unsupported_unless_explicitly_planned"
#   runtime_artifacts:
#     directory: "state/daemon"
#     files:
#       - "daemon.pid"
#       - "daemon.sock_or_pipe_metadata"
#       - "daemon-state.json"
#       - "daemon.log"
#       - "daemon.lock"
#       - "auth.token_when_tcp_enabled"

approved_by: "{{user}}"
approved_at: "{{iso8601_timestamp}}"
