# cli-plan.yml
#
# Generated by the Plan stage (Stage 2) and consumed by Scaffold (Stage 3),
# Extend (Stage 4), and Validate (Stage 5) as the authoritative CLI contract.
# Stored at: <target-project>/.cli-forge/cli-plan.yml

skill_name: "{{skill_name}}"
design_contract: "./design-contract.yml"

invocation:
  shipped: "{{skill_name}}"
  dev: "cargo run --"
  release_binary: "./target/release/{{skill_name}}"

commands:
  - name: "{{command_name}}"
    description: "{{command_description}}"
    flags:
      - name: "{{--flag-name}}"
        type: "{{string|path|bool|enum|int}}"
        required: "{{true|false}}"
        default: "{{default_value}}"
        values: []                    # only for enum type
        description: "{{flag_description}}"
    output_formats: ["yaml", "json", "toml"]
    error_format: "structured_stderr"

  - name: "help"
    description: "Structured help output"
    flags:
      - name: "--format"
        type: "enum"
        required: false
        default: "yaml"
        values: ["yaml", "json"]
        description: "Output format for structured help"

help:
  plain_text: "--help flag on any command"
  structured: "help subcommand with --format"

capabilities:
  stream: "{{in_scope|out_of_scope}}"
  repl: "{{in_scope|out_of_scope}}"
  daemon: "{{in_scope|out_of_scope}}"

runtime:
  directory: "~/.{{skill_name}}/"
  active_context: "{{true|false}}"
  context_override: "--context flag"

# Include this section only when daemon capability is in_scope
daemon_contract:
  mode: "managed_background"
  instance_model: "single"
  lifecycle:
    - "start"
    - "stop"
    - "restart"
    - "status"
  return_on:
    - "running"
    - "stopped"
    - "failed"
    - "timeout"
  transports:
    stdio: "--transport stdio"
    tcp: "--transport tcp --port N"
    unix: "--transport unix --socket PATH"
  websocket: true
  tls: "--cert-file and --key-file"
  auth_modes:
    - "capability-token"
    - "signed-bearer-token"

approved_by: "{{user}}"
approved_at: "{{iso8601_timestamp}}"
