# release-receipt.yml
#
# Generated by the Publish stage (Stage 6) after completing a release activity.
# Stored at: <target-project>/.cli-forge/release-receipt.yml
#
# The receipt is a human-written record of what the user actually did. It does
# not replicate information that already lives in the GitHub Release page, the
# workflow run, or the npm registry.

project: "{{skill_name}}"
project_path: "{{project_path}}"
timestamp: "{{iso8601_timestamp}}"

release_mode: "{{report_only|dry_run|live_release}}"

# Only present for dry_run and live_release
version: "{{semver|null}}"
git_tag: "{{v_semver|null}}"
workflow_run_url: "{{github_actions_run_url|null}}"

npm:
  main_package: "{{package_name}}"
  scope: "{{null_or_scope_string}}"
  platform_package_count: "{{target_count}}"

validation_report_ref: "./validation-report.yml"

outcome: "{{success|dry_run_reviewed|report_delivered}}"
